modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/AzureDoom/Dark-Waters/issues"
license="MIT"
[[mods]]
modId="darkwaters"
version="${mod_version}"
displayName="Dark Waters"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dark-waters"
logoFile="assets/darkwaters/icon.png"
credits="AzureDoom, Batpixxler, Assasingus14"
authors="AzureDoom, Batpixxler, Assasingus14"
description='''If you hear the thunder....it's already too late.'''
[[dependencies.darkwaters]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.darkwaters]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.darkwaters]]
    modId="azurelib"
    mandatory=true
    versionRange="[2.0.11,)"
    ordering="BEFORE"
    side="BOTH"